/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActivityLevel = { 'Sedentary' : null } |
  { 'VeryActive' : null } |
  { 'LightlyActive' : null } |
  { 'ModeratelyActive' : null } |
  { 'ExtraActive' : null };
export interface AddFoodLogRequest { 'calories' : bigint, 'mealName' : string }
export type BMICategory = { 'Normal' : null } |
  { 'Overweight' : null } |
  { 'Obese' : null } |
  { 'Underweight' : null };
export interface CreateProfileRequest {
  'age' : bigint,
  'activityLevel' : ActivityLevel,
  'heightCm' : number,
  'goal' : Goal,
  'name' : string,
  'weightKg' : number,
  'gender' : Gender,
  'dietaryPreference' : DietaryPreference,
}
export interface DietPlan {
  'meals' : Array<Meal>,
  'userId' : UserId,
  'dailyCaloricTarget' : bigint,
}
export type DietaryPreference = { 'Vegetarian' : null } |
  { 'NonVegetarian' : null };
export interface Exercise {
  'id' : Id,
  'durationSecs' : [] | [bigint],
  'fitnessLevel' : FitnessLevel,
  'name' : string,
  'reps' : [] | [bigint],
  'description' : string,
  'muscleGroup' : MuscleGroup,
  'youtubeUrl' : string,
}
export type FitnessLevel = { 'Beginner' : null } |
  { 'Advanced' : null } |
  { 'Intermediate' : null };
export interface FoodLogEntry {
  'id' : Id,
  'userId' : UserId,
  'calories' : bigint,
  'timestamp' : Timestamp,
  'mealName' : string,
}
export type Gender = { 'Male' : null } |
  { 'Female' : null };
export type Goal = { 'Maintain' : null } |
  { 'GainWeight' : null } |
  { 'LoseWeight' : null };
export interface HealthMetricLog {
  'id' : Id,
  'bmi' : number,
  'bmr' : number,
  'heightCm' : number,
  'bmiCategory' : BMICategory,
  'userId' : UserId,
  'weightKg' : number,
  'timestamp' : Timestamp,
}
export interface HealthSummary {
  'bmiCategory' : BMICategory,
  'latestBMI' : number,
  'latestBMR' : number,
  'dailyCaloricNeeds' : number,
}
export type Id = bigint;
export interface LogWorkoutRequest {
  'completed' : boolean,
  'routineName' : string,
  'notes' : string,
}
export interface Meal {
  'id' : Id,
  'fatG' : number,
  'calories' : bigint,
  'name' : string,
  'description' : string,
  'isVegetarian' : boolean,
  'category' : MealCategory,
  'carbsG' : number,
  'prepTimeMinutes' : bigint,
  'proteinG' : number,
}
export type MealCategory = { 'Lunch' : null } |
  { 'Snack' : null } |
  { 'Breakfast' : null } |
  { 'Dinner' : null };
export type MuscleGroup = { 'Arms' : null } |
  { 'Back' : null } |
  { 'Core' : null } |
  { 'FullBody' : null } |
  { 'Legs' : null } |
  { 'Chest' : null } |
  { 'Cardio' : null };
export interface ProgressRecord {
  'id' : Id,
  'bmi' : number,
  'userId' : UserId,
  'date' : string,
  'weightKg' : number,
  'dailyCalories' : bigint,
  'workoutsCompleted' : bigint,
}
export type Timestamp = bigint;
export interface UpdateProfileRequest {
  'age' : [] | [bigint],
  'activityLevel' : [] | [ActivityLevel],
  'heightCm' : [] | [number],
  'goal' : [] | [Goal],
  'name' : [] | [string],
  'weightKg' : [] | [number],
  'gender' : [] | [Gender],
  'dietaryPreference' : [] | [DietaryPreference],
}
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'age' : bigint,
  'activityLevel' : ActivityLevel,
  'heightCm' : number,
  'goal' : Goal,
  'name' : string,
  'createdAt' : Timestamp,
  'weightKg' : number,
  'gender' : Gender,
  'dietaryPreference' : DietaryPreference,
}
export interface WeeklyStats {
  'streak' : bigint,
  'averageDailyCalories' : number,
  'weekStartDate' : string,
  'totalWorkouts' : bigint,
  'averageBMI' : number,
}
export interface WorkoutLogEntry {
  'id' : Id,
  'userId' : UserId,
  'date' : Timestamp,
  'completed' : boolean,
  'routineName' : string,
  'notes' : string,
}
export interface WorkoutRoutine {
  'id' : Id,
  'fitnessLevel' : FitnessLevel,
  'exerciseIds' : Array<Id>,
  'name' : string,
  'description' : string,
}
export interface _SERVICE {
  'addFoodLog' : ActorMethod<[AddFoodLogRequest], FoodLogEntry>,
  'createMyProfile' : ActorMethod<[CreateProfileRequest], UserProfilePublic>,
  'getExerciseById' : ActorMethod<[Id], [] | [Exercise]>,
  'getExercises' : ActorMethod<
    [[] | [MuscleGroup], [] | [FitnessLevel]],
    Array<Exercise>
  >,
  'getHealthLogs' : ActorMethod<[], Array<HealthMetricLog>>,
  'getHealthSummary' : ActorMethod<[], [] | [HealthSummary]>,
  'getMealById' : ActorMethod<[Id], [] | [Meal]>,
  'getMeals' : ActorMethod<[[] | [boolean], [] | [MealCategory]], Array<Meal>>,
  'getMyDietPlan' : ActorMethod<[], [] | [DietPlan]>,
  'getMyFoodLogs' : ActorMethod<[], Array<FoodLogEntry>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getMyWorkoutLogs' : ActorMethod<[], Array<WorkoutLogEntry>>,
  'getProgressHistory' : ActorMethod<[], Array<ProgressRecord>>,
  'getRecentProgress' : ActorMethod<[bigint], Array<ProgressRecord>>,
  'getRoutineById' : ActorMethod<[Id], [] | [WorkoutRoutine]>,
  'getRoutines' : ActorMethod<[[] | [FitnessLevel]], Array<WorkoutRoutine>>,
  'getTodayCalories' : ActorMethod<[], bigint>,
  'getWeeklyStats' : ActorMethod<[], [] | [WeeklyStats]>,
  'hasProfile' : ActorMethod<[], boolean>,
  'logHealthMetrics' : ActorMethod<[], HealthMetricLog>,
  'logWorkout' : ActorMethod<[LogWorkoutRequest], WorkoutLogEntry>,
  'recordDailyProgress' : ActorMethod<
    [number, number, bigint, bigint],
    ProgressRecord
  >,
  'updateMyProfile' : ActorMethod<
    [UpdateProfileRequest],
    [] | [UserProfilePublic]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];