/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AddFoodLogRequest = IDL.Record({
  'calories' : IDL.Nat,
  'mealName' : IDL.Text,
});
export const Id = IDL.Nat;
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const FoodLogEntry = IDL.Record({
  'id' : Id,
  'userId' : UserId,
  'calories' : IDL.Nat,
  'timestamp' : Timestamp,
  'mealName' : IDL.Text,
});
export const ActivityLevel = IDL.Variant({
  'Sedentary' : IDL.Null,
  'VeryActive' : IDL.Null,
  'LightlyActive' : IDL.Null,
  'ModeratelyActive' : IDL.Null,
  'ExtraActive' : IDL.Null,
});
export const Goal = IDL.Variant({
  'Maintain' : IDL.Null,
  'GainWeight' : IDL.Null,
  'LoseWeight' : IDL.Null,
});
export const Gender = IDL.Variant({ 'Male' : IDL.Null, 'Female' : IDL.Null });
export const DietaryPreference = IDL.Variant({
  'Vegetarian' : IDL.Null,
  'NonVegetarian' : IDL.Null,
});
export const CreateProfileRequest = IDL.Record({
  'age' : IDL.Nat,
  'activityLevel' : ActivityLevel,
  'heightCm' : IDL.Float64,
  'goal' : Goal,
  'name' : IDL.Text,
  'weightKg' : IDL.Float64,
  'gender' : Gender,
  'dietaryPreference' : DietaryPreference,
});
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'age' : IDL.Nat,
  'activityLevel' : ActivityLevel,
  'heightCm' : IDL.Float64,
  'goal' : Goal,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'weightKg' : IDL.Float64,
  'gender' : Gender,
  'dietaryPreference' : DietaryPreference,
});
export const FitnessLevel = IDL.Variant({
  'Beginner' : IDL.Null,
  'Advanced' : IDL.Null,
  'Intermediate' : IDL.Null,
});
export const MuscleGroup = IDL.Variant({
  'Arms' : IDL.Null,
  'Back' : IDL.Null,
  'Core' : IDL.Null,
  'FullBody' : IDL.Null,
  'Legs' : IDL.Null,
  'Chest' : IDL.Null,
  'Cardio' : IDL.Null,
});
export const Exercise = IDL.Record({
  'id' : Id,
  'durationSecs' : IDL.Opt(IDL.Nat),
  'fitnessLevel' : FitnessLevel,
  'name' : IDL.Text,
  'reps' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
  'muscleGroup' : MuscleGroup,
  'youtubeUrl' : IDL.Text,
});
export const BMICategory = IDL.Variant({
  'Normal' : IDL.Null,
  'Overweight' : IDL.Null,
  'Obese' : IDL.Null,
  'Underweight' : IDL.Null,
});
export const HealthMetricLog = IDL.Record({
  'id' : Id,
  'bmi' : IDL.Float64,
  'bmr' : IDL.Float64,
  'heightCm' : IDL.Float64,
  'bmiCategory' : BMICategory,
  'userId' : UserId,
  'weightKg' : IDL.Float64,
  'timestamp' : Timestamp,
});
export const HealthSummary = IDL.Record({
  'bmiCategory' : BMICategory,
  'latestBMI' : IDL.Float64,
  'latestBMR' : IDL.Float64,
  'dailyCaloricNeeds' : IDL.Float64,
});
export const MealCategory = IDL.Variant({
  'Lunch' : IDL.Null,
  'Snack' : IDL.Null,
  'Breakfast' : IDL.Null,
  'Dinner' : IDL.Null,
});
export const Meal = IDL.Record({
  'id' : Id,
  'fatG' : IDL.Float64,
  'calories' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isVegetarian' : IDL.Bool,
  'category' : MealCategory,
  'carbsG' : IDL.Float64,
  'prepTimeMinutes' : IDL.Nat,
  'proteinG' : IDL.Float64,
});
export const DietPlan = IDL.Record({
  'meals' : IDL.Vec(Meal),
  'userId' : UserId,
  'dailyCaloricTarget' : IDL.Nat,
});
export const WorkoutLogEntry = IDL.Record({
  'id' : Id,
  'userId' : UserId,
  'date' : Timestamp,
  'completed' : IDL.Bool,
  'routineName' : IDL.Text,
  'notes' : IDL.Text,
});
export const ProgressRecord = IDL.Record({
  'id' : Id,
  'bmi' : IDL.Float64,
  'userId' : UserId,
  'date' : IDL.Text,
  'weightKg' : IDL.Float64,
  'dailyCalories' : IDL.Nat,
  'workoutsCompleted' : IDL.Nat,
});
export const WorkoutRoutine = IDL.Record({
  'id' : Id,
  'fitnessLevel' : FitnessLevel,
  'exerciseIds' : IDL.Vec(Id),
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const WeeklyStats = IDL.Record({
  'streak' : IDL.Nat,
  'averageDailyCalories' : IDL.Float64,
  'weekStartDate' : IDL.Text,
  'totalWorkouts' : IDL.Nat,
  'averageBMI' : IDL.Float64,
});
export const LogWorkoutRequest = IDL.Record({
  'completed' : IDL.Bool,
  'routineName' : IDL.Text,
  'notes' : IDL.Text,
});
export const UpdateProfileRequest = IDL.Record({
  'age' : IDL.Opt(IDL.Nat),
  'activityLevel' : IDL.Opt(ActivityLevel),
  'heightCm' : IDL.Opt(IDL.Float64),
  'goal' : IDL.Opt(Goal),
  'name' : IDL.Opt(IDL.Text),
  'weightKg' : IDL.Opt(IDL.Float64),
  'gender' : IDL.Opt(Gender),
  'dietaryPreference' : IDL.Opt(DietaryPreference),
});

export const idlService = IDL.Service({
  'addFoodLog' : IDL.Func([AddFoodLogRequest], [FoodLogEntry], []),
  'createMyProfile' : IDL.Func([CreateProfileRequest], [UserProfilePublic], []),
  'getExerciseById' : IDL.Func([Id], [IDL.Opt(Exercise)], ['query']),
  'getExercises' : IDL.Func(
      [IDL.Opt(MuscleGroup), IDL.Opt(FitnessLevel)],
      [IDL.Vec(Exercise)],
      ['query'],
    ),
  'getHealthLogs' : IDL.Func([], [IDL.Vec(HealthMetricLog)], ['query']),
  'getHealthSummary' : IDL.Func([], [IDL.Opt(HealthSummary)], ['query']),
  'getMealById' : IDL.Func([Id], [IDL.Opt(Meal)], ['query']),
  'getMeals' : IDL.Func(
      [IDL.Opt(IDL.Bool), IDL.Opt(MealCategory)],
      [IDL.Vec(Meal)],
      ['query'],
    ),
  'getMyDietPlan' : IDL.Func([], [IDL.Opt(DietPlan)], ['query']),
  'getMyFoodLogs' : IDL.Func([], [IDL.Vec(FoodLogEntry)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], []),
  'getMyWorkoutLogs' : IDL.Func([], [IDL.Vec(WorkoutLogEntry)], ['query']),
  'getProgressHistory' : IDL.Func([], [IDL.Vec(ProgressRecord)], ['query']),
  'getRecentProgress' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ProgressRecord)],
      ['query'],
    ),
  'getRoutineById' : IDL.Func([Id], [IDL.Opt(WorkoutRoutine)], ['query']),
  'getRoutines' : IDL.Func(
      [IDL.Opt(FitnessLevel)],
      [IDL.Vec(WorkoutRoutine)],
      ['query'],
    ),
  'getTodayCalories' : IDL.Func([], [IDL.Nat], ['query']),
  'getWeeklyStats' : IDL.Func([], [IDL.Opt(WeeklyStats)], ['query']),
  'hasProfile' : IDL.Func([], [IDL.Bool], ['query']),
  'logHealthMetrics' : IDL.Func([], [HealthMetricLog], []),
  'logWorkout' : IDL.Func([LogWorkoutRequest], [WorkoutLogEntry], []),
  'recordDailyProgress' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Nat, IDL.Nat],
      [ProgressRecord],
      [],
    ),
  'updateMyProfile' : IDL.Func(
      [UpdateProfileRequest],
      [IDL.Opt(UserProfilePublic)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AddFoodLogRequest = IDL.Record({
    'calories' : IDL.Nat,
    'mealName' : IDL.Text,
  });
  const Id = IDL.Nat;
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const FoodLogEntry = IDL.Record({
    'id' : Id,
    'userId' : UserId,
    'calories' : IDL.Nat,
    'timestamp' : Timestamp,
    'mealName' : IDL.Text,
  });
  const ActivityLevel = IDL.Variant({
    'Sedentary' : IDL.Null,
    'VeryActive' : IDL.Null,
    'LightlyActive' : IDL.Null,
    'ModeratelyActive' : IDL.Null,
    'ExtraActive' : IDL.Null,
  });
  const Goal = IDL.Variant({
    'Maintain' : IDL.Null,
    'GainWeight' : IDL.Null,
    'LoseWeight' : IDL.Null,
  });
  const Gender = IDL.Variant({ 'Male' : IDL.Null, 'Female' : IDL.Null });
  const DietaryPreference = IDL.Variant({
    'Vegetarian' : IDL.Null,
    'NonVegetarian' : IDL.Null,
  });
  const CreateProfileRequest = IDL.Record({
    'age' : IDL.Nat,
    'activityLevel' : ActivityLevel,
    'heightCm' : IDL.Float64,
    'goal' : Goal,
    'name' : IDL.Text,
    'weightKg' : IDL.Float64,
    'gender' : Gender,
    'dietaryPreference' : DietaryPreference,
  });
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'age' : IDL.Nat,
    'activityLevel' : ActivityLevel,
    'heightCm' : IDL.Float64,
    'goal' : Goal,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'weightKg' : IDL.Float64,
    'gender' : Gender,
    'dietaryPreference' : DietaryPreference,
  });
  const FitnessLevel = IDL.Variant({
    'Beginner' : IDL.Null,
    'Advanced' : IDL.Null,
    'Intermediate' : IDL.Null,
  });
  const MuscleGroup = IDL.Variant({
    'Arms' : IDL.Null,
    'Back' : IDL.Null,
    'Core' : IDL.Null,
    'FullBody' : IDL.Null,
    'Legs' : IDL.Null,
    'Chest' : IDL.Null,
    'Cardio' : IDL.Null,
  });
  const Exercise = IDL.Record({
    'id' : Id,
    'durationSecs' : IDL.Opt(IDL.Nat),
    'fitnessLevel' : FitnessLevel,
    'name' : IDL.Text,
    'reps' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
    'muscleGroup' : MuscleGroup,
    'youtubeUrl' : IDL.Text,
  });
  const BMICategory = IDL.Variant({
    'Normal' : IDL.Null,
    'Overweight' : IDL.Null,
    'Obese' : IDL.Null,
    'Underweight' : IDL.Null,
  });
  const HealthMetricLog = IDL.Record({
    'id' : Id,
    'bmi' : IDL.Float64,
    'bmr' : IDL.Float64,
    'heightCm' : IDL.Float64,
    'bmiCategory' : BMICategory,
    'userId' : UserId,
    'weightKg' : IDL.Float64,
    'timestamp' : Timestamp,
  });
  const HealthSummary = IDL.Record({
    'bmiCategory' : BMICategory,
    'latestBMI' : IDL.Float64,
    'latestBMR' : IDL.Float64,
    'dailyCaloricNeeds' : IDL.Float64,
  });
  const MealCategory = IDL.Variant({
    'Lunch' : IDL.Null,
    'Snack' : IDL.Null,
    'Breakfast' : IDL.Null,
    'Dinner' : IDL.Null,
  });
  const Meal = IDL.Record({
    'id' : Id,
    'fatG' : IDL.Float64,
    'calories' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isVegetarian' : IDL.Bool,
    'category' : MealCategory,
    'carbsG' : IDL.Float64,
    'prepTimeMinutes' : IDL.Nat,
    'proteinG' : IDL.Float64,
  });
  const DietPlan = IDL.Record({
    'meals' : IDL.Vec(Meal),
    'userId' : UserId,
    'dailyCaloricTarget' : IDL.Nat,
  });
  const WorkoutLogEntry = IDL.Record({
    'id' : Id,
    'userId' : UserId,
    'date' : Timestamp,
    'completed' : IDL.Bool,
    'routineName' : IDL.Text,
    'notes' : IDL.Text,
  });
  const ProgressRecord = IDL.Record({
    'id' : Id,
    'bmi' : IDL.Float64,
    'userId' : UserId,
    'date' : IDL.Text,
    'weightKg' : IDL.Float64,
    'dailyCalories' : IDL.Nat,
    'workoutsCompleted' : IDL.Nat,
  });
  const WorkoutRoutine = IDL.Record({
    'id' : Id,
    'fitnessLevel' : FitnessLevel,
    'exerciseIds' : IDL.Vec(Id),
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const WeeklyStats = IDL.Record({
    'streak' : IDL.Nat,
    'averageDailyCalories' : IDL.Float64,
    'weekStartDate' : IDL.Text,
    'totalWorkouts' : IDL.Nat,
    'averageBMI' : IDL.Float64,
  });
  const LogWorkoutRequest = IDL.Record({
    'completed' : IDL.Bool,
    'routineName' : IDL.Text,
    'notes' : IDL.Text,
  });
  const UpdateProfileRequest = IDL.Record({
    'age' : IDL.Opt(IDL.Nat),
    'activityLevel' : IDL.Opt(ActivityLevel),
    'heightCm' : IDL.Opt(IDL.Float64),
    'goal' : IDL.Opt(Goal),
    'name' : IDL.Opt(IDL.Text),
    'weightKg' : IDL.Opt(IDL.Float64),
    'gender' : IDL.Opt(Gender),
    'dietaryPreference' : IDL.Opt(DietaryPreference),
  });
  
  return IDL.Service({
    'addFoodLog' : IDL.Func([AddFoodLogRequest], [FoodLogEntry], []),
    'createMyProfile' : IDL.Func(
        [CreateProfileRequest],
        [UserProfilePublic],
        [],
      ),
    'getExerciseById' : IDL.Func([Id], [IDL.Opt(Exercise)], ['query']),
    'getExercises' : IDL.Func(
        [IDL.Opt(MuscleGroup), IDL.Opt(FitnessLevel)],
        [IDL.Vec(Exercise)],
        ['query'],
      ),
    'getHealthLogs' : IDL.Func([], [IDL.Vec(HealthMetricLog)], ['query']),
    'getHealthSummary' : IDL.Func([], [IDL.Opt(HealthSummary)], ['query']),
    'getMealById' : IDL.Func([Id], [IDL.Opt(Meal)], ['query']),
    'getMeals' : IDL.Func(
        [IDL.Opt(IDL.Bool), IDL.Opt(MealCategory)],
        [IDL.Vec(Meal)],
        ['query'],
      ),
    'getMyDietPlan' : IDL.Func([], [IDL.Opt(DietPlan)], ['query']),
    'getMyFoodLogs' : IDL.Func([], [IDL.Vec(FoodLogEntry)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], []),
    'getMyWorkoutLogs' : IDL.Func([], [IDL.Vec(WorkoutLogEntry)], ['query']),
    'getProgressHistory' : IDL.Func([], [IDL.Vec(ProgressRecord)], ['query']),
    'getRecentProgress' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ProgressRecord)],
        ['query'],
      ),
    'getRoutineById' : IDL.Func([Id], [IDL.Opt(WorkoutRoutine)], ['query']),
    'getRoutines' : IDL.Func(
        [IDL.Opt(FitnessLevel)],
        [IDL.Vec(WorkoutRoutine)],
        ['query'],
      ),
    'getTodayCalories' : IDL.Func([], [IDL.Nat], ['query']),
    'getWeeklyStats' : IDL.Func([], [IDL.Opt(WeeklyStats)], ['query']),
    'hasProfile' : IDL.Func([], [IDL.Bool], ['query']),
    'logHealthMetrics' : IDL.Func([], [HealthMetricLog], []),
    'logWorkout' : IDL.Func([LogWorkoutRequest], [WorkoutLogEntry], []),
    'recordDailyProgress' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Nat, IDL.Nat],
        [ProgressRecord],
        [],
      ),
    'updateMyProfile' : IDL.Func(
        [UpdateProfileRequest],
        [IDL.Opt(UserProfilePublic)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };