/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Meal {
    id: Id;
    fatG: number;
    calories: bigint;
    name: string;
    description: string;
    isVegetarian: boolean;
    category: MealCategory;
    carbsG: number;
    prepTimeMinutes: bigint;
    proteinG: number;
}
export interface FoodLogEntry {
    id: Id;
    userId: UserId;
    calories: bigint;
    timestamp: Timestamp;
    mealName: string;
}
export type Timestamp = bigint;
export interface Exercise {
    id: Id;
    durationSecs?: bigint;
    fitnessLevel: FitnessLevel;
    name: string;
    reps?: bigint;
    description: string;
    muscleGroup: MuscleGroup;
    youtubeUrl: string;
}
export interface CreateProfileRequest {
    age: bigint;
    activityLevel: ActivityLevel;
    heightCm: number;
    goal: Goal;
    name: string;
    weightKg: number;
    gender: Gender;
    dietaryPreference: DietaryPreference;
}
export interface WorkoutRoutine {
    id: Id;
    fitnessLevel: FitnessLevel;
    exerciseIds: Array<Id>;
    name: string;
    description: string;
}
export interface UserProfilePublic {
    id: UserId;
    age: bigint;
    activityLevel: ActivityLevel;
    heightCm: number;
    goal: Goal;
    name: string;
    createdAt: Timestamp;
    weightKg: number;
    gender: Gender;
    dietaryPreference: DietaryPreference;
}
export interface AddFoodLogRequest {
    calories: bigint;
    mealName: string;
}
export type UserId = Principal;
export interface WeeklyStats {
    streak: bigint;
    averageDailyCalories: number;
    weekStartDate: string;
    totalWorkouts: bigint;
    averageBMI: number;
}
export interface UpdateProfileRequest {
    age?: bigint;
    activityLevel?: ActivityLevel;
    heightCm?: number;
    goal?: Goal;
    name?: string;
    weightKg?: number;
    gender?: Gender;
    dietaryPreference?: DietaryPreference;
}
export interface ProgressRecord {
    id: Id;
    bmi: number;
    userId: UserId;
    date: string;
    weightKg: number;
    dailyCalories: bigint;
    workoutsCompleted: bigint;
}
export interface LogWorkoutRequest {
    completed: boolean;
    routineName: string;
    notes: string;
}
export type Id = bigint;
export interface HealthMetricLog {
    id: Id;
    bmi: number;
    bmr: number;
    heightCm: number;
    bmiCategory: BMICategory;
    userId: UserId;
    weightKg: number;
    timestamp: Timestamp;
}
export interface HealthSummary {
    bmiCategory: BMICategory;
    latestBMI: number;
    latestBMR: number;
    dailyCaloricNeeds: number;
}
export interface DietPlan {
    meals: Array<Meal>;
    userId: UserId;
    dailyCaloricTarget: bigint;
}
export interface WorkoutLogEntry {
    id: Id;
    userId: UserId;
    date: Timestamp;
    completed: boolean;
    routineName: string;
    notes: string;
}
export enum ActivityLevel {
    Sedentary = "Sedentary",
    VeryActive = "VeryActive",
    LightlyActive = "LightlyActive",
    ModeratelyActive = "ModeratelyActive",
    ExtraActive = "ExtraActive"
}
export enum BMICategory {
    Normal = "Normal",
    Overweight = "Overweight",
    Obese = "Obese",
    Underweight = "Underweight"
}
export enum DietaryPreference {
    Vegetarian = "Vegetarian",
    NonVegetarian = "NonVegetarian"
}
export enum FitnessLevel {
    Beginner = "Beginner",
    Advanced = "Advanced",
    Intermediate = "Intermediate"
}
export enum Gender {
    Male = "Male",
    Female = "Female"
}
export enum Goal {
    Maintain = "Maintain",
    GainWeight = "GainWeight",
    LoseWeight = "LoseWeight"
}
export enum MealCategory {
    Lunch = "Lunch",
    Snack = "Snack",
    Breakfast = "Breakfast",
    Dinner = "Dinner"
}
export enum MuscleGroup {
    Arms = "Arms",
    Back = "Back",
    Core = "Core",
    FullBody = "FullBody",
    Legs = "Legs",
    Chest = "Chest",
    Cardio = "Cardio"
}
export interface backendInterface {
    addFoodLog(req: AddFoodLogRequest): Promise<FoodLogEntry>;
    createMyProfile(req: CreateProfileRequest): Promise<UserProfilePublic>;
    getExerciseById(exerciseId: Id): Promise<Exercise | null>;
    getExercises(muscleGroup: MuscleGroup | null, fitnessLevel: FitnessLevel | null): Promise<Array<Exercise>>;
    getHealthLogs(): Promise<Array<HealthMetricLog>>;
    getHealthSummary(): Promise<HealthSummary | null>;
    getMealById(mealId: Id): Promise<Meal | null>;
    getMeals(isVegetarian: boolean | null, category: MealCategory | null): Promise<Array<Meal>>;
    getMyDietPlan(): Promise<DietPlan | null>;
    getMyFoodLogs(): Promise<Array<FoodLogEntry>>;
    getMyProfile(): Promise<UserProfilePublic | null>;
    getMyWorkoutLogs(): Promise<Array<WorkoutLogEntry>>;
    getProgressHistory(): Promise<Array<ProgressRecord>>;
    getRecentProgress(limitDays: bigint): Promise<Array<ProgressRecord>>;
    getRoutineById(routineId: Id): Promise<WorkoutRoutine | null>;
    getRoutines(fitnessLevel: FitnessLevel | null): Promise<Array<WorkoutRoutine>>;
    getTodayCalories(): Promise<bigint>;
    getWeeklyStats(): Promise<WeeklyStats | null>;
    hasProfile(): Promise<boolean>;
    logHealthMetrics(): Promise<HealthMetricLog>;
    logWorkout(req: LogWorkoutRequest): Promise<WorkoutLogEntry>;
    recordDailyProgress(bmi: number, weightKg: number, dailyCalories: bigint, workoutsCompleted: bigint): Promise<ProgressRecord>;
    updateMyProfile(req: UpdateProfileRequest): Promise<UserProfilePublic | null>;
}
import type { ActivityLevel as _ActivityLevel, BMICategory as _BMICategory, CreateProfileRequest as _CreateProfileRequest, DietPlan as _DietPlan, DietaryPreference as _DietaryPreference, Exercise as _Exercise, FitnessLevel as _FitnessLevel, Gender as _Gender, Goal as _Goal, HealthMetricLog as _HealthMetricLog, HealthSummary as _HealthSummary, Id as _Id, Meal as _Meal, MealCategory as _MealCategory, MuscleGroup as _MuscleGroup, Timestamp as _Timestamp, UpdateProfileRequest as _UpdateProfileRequest, UserId as _UserId, UserProfilePublic as _UserProfilePublic, WeeklyStats as _WeeklyStats, WorkoutRoutine as _WorkoutRoutine } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addFoodLog(arg0: AddFoodLogRequest): Promise<FoodLogEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.addFoodLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFoodLog(arg0);
            return result;
        }
    }
    async createMyProfile(arg0: CreateProfileRequest): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createMyProfile(to_candid_CreateProfileRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserProfilePublic_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMyProfile(to_candid_CreateProfileRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserProfilePublic_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExerciseById(arg0: Id): Promise<Exercise | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExerciseById(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExerciseById(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExercises(arg0: MuscleGroup | null, arg1: FitnessLevel | null): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExercises(to_candid_opt_n29(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExercises(to_candid_opt_n29(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHealthLogs(): Promise<Array<HealthMetricLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHealthLogs();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHealthLogs();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHealthSummary(): Promise<HealthSummary | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHealthSummary();
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHealthSummary();
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMealById(arg0: Id): Promise<Meal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMealById(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMealById(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMeals(arg0: boolean | null, arg1: MealCategory | null): Promise<Array<Meal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMeals(to_candid_opt_n49(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMeals(to_candid_opt_n49(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyDietPlan(): Promise<DietPlan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDietPlan();
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDietPlan();
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyFoodLogs(): Promise<Array<FoodLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyFoodLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyFoodLogs();
            return result;
        }
    }
    async getMyProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWorkoutLogs(): Promise<Array<WorkoutLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWorkoutLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWorkoutLogs();
            return result;
        }
    }
    async getProgressHistory(): Promise<Array<ProgressRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgressHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgressHistory();
            return result;
        }
    }
    async getRecentProgress(arg0: bigint): Promise<Array<ProgressRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentProgress(arg0);
            return result;
        }
    }
    async getRoutineById(arg0: Id): Promise<WorkoutRoutine | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoutineById(arg0);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoutineById(arg0);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoutines(arg0: FitnessLevel | null): Promise<Array<WorkoutRoutine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoutines(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoutines(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodayCalories(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodayCalories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodayCalories();
            return result;
        }
    }
    async getWeeklyStats(): Promise<WeeklyStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyStats();
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyStats();
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasProfile(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasProfile();
            return result;
        }
    }
    async logHealthMetrics(): Promise<HealthMetricLog> {
        if (this.processError) {
            try {
                const result = await this.actor.logHealthMetrics();
                return from_candid_HealthMetricLog_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logHealthMetrics();
            return from_candid_HealthMetricLog_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async logWorkout(arg0: LogWorkoutRequest): Promise<WorkoutLogEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.logWorkout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWorkout(arg0);
            return result;
        }
    }
    async recordDailyProgress(arg0: number, arg1: number, arg2: bigint, arg3: bigint): Promise<ProgressRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.recordDailyProgress(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordDailyProgress(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateMyProfile(arg0: UpdateProfileRequest): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(to_candid_UpdateProfileRequest_n63(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(to_candid_UpdateProfileRequest_n63(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ActivityLevel_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityLevel): ActivityLevel {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_BMICategory_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BMICategory): BMICategory {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_DietPlan_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DietPlan): DietPlan {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_DietaryPreference_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DietaryPreference): DietaryPreference {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Exercise_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Exercise): Exercise {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_FitnessLevel_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FitnessLevel): FitnessLevel {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Goal_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Goal): Goal {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_HealthMetricLog_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthMetricLog): HealthMetricLog {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_HealthSummary_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthSummary): HealthSummary {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_MealCategory_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MealCategory): MealCategory {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_Meal_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Meal): Meal {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_MuscleGroup_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MuscleGroup): MuscleGroup {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutRoutine_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutRoutine): WorkoutRoutine {
    return from_candid_record_n60(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Exercise]): Exercise | null {
    return value.length === 0 ? null : from_candid_Exercise_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HealthSummary]): HealthSummary | null {
    return value.length === 0 ? null : from_candid_HealthSummary_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Meal]): Meal | null {
    return value.length === 0 ? null : from_candid_Meal_n45(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DietPlan]): DietPlan | null {
    return value.length === 0 ? null : from_candid_DietPlan_n55(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WorkoutRoutine]): WorkoutRoutine | null {
    return value.length === 0 ? null : from_candid_WorkoutRoutine_n59(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WeeklyStats]): WeeklyStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    age: bigint;
    activityLevel: _ActivityLevel;
    heightCm: number;
    goal: _Goal;
    name: string;
    createdAt: _Timestamp;
    weightKg: number;
    gender: _Gender;
    dietaryPreference: _DietaryPreference;
}): {
    id: UserId;
    age: bigint;
    activityLevel: ActivityLevel;
    heightCm: number;
    goal: Goal;
    name: string;
    createdAt: Timestamp;
    weightKg: number;
    gender: Gender;
    dietaryPreference: DietaryPreference;
} {
    return {
        id: value.id,
        age: value.age,
        activityLevel: from_candid_ActivityLevel_n13(_uploadFile, _downloadFile, value.activityLevel),
        heightCm: value.heightCm,
        goal: from_candid_Goal_n15(_uploadFile, _downloadFile, value.goal),
        name: value.name,
        createdAt: value.createdAt,
        weightKg: value.weightKg,
        gender: from_candid_Gender_n17(_uploadFile, _downloadFile, value.gender),
        dietaryPreference: from_candid_DietaryPreference_n19(_uploadFile, _downloadFile, value.dietaryPreference)
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    durationSecs: [] | [bigint];
    fitnessLevel: _FitnessLevel;
    name: string;
    reps: [] | [bigint];
    description: string;
    muscleGroup: _MuscleGroup;
    youtubeUrl: string;
}): {
    id: Id;
    durationSecs?: bigint;
    fitnessLevel: FitnessLevel;
    name: string;
    reps?: bigint;
    description: string;
    muscleGroup: MuscleGroup;
    youtubeUrl: string;
} {
    return {
        id: value.id,
        durationSecs: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.durationSecs)),
        fitnessLevel: from_candid_FitnessLevel_n25(_uploadFile, _downloadFile, value.fitnessLevel),
        name: value.name,
        reps: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.reps)),
        description: value.description,
        muscleGroup: from_candid_MuscleGroup_n27(_uploadFile, _downloadFile, value.muscleGroup),
        youtubeUrl: value.youtubeUrl
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    bmi: number;
    bmr: number;
    heightCm: number;
    bmiCategory: _BMICategory;
    userId: _UserId;
    weightKg: number;
    timestamp: _Timestamp;
}): {
    id: Id;
    bmi: number;
    bmr: number;
    heightCm: number;
    bmiCategory: BMICategory;
    userId: UserId;
    weightKg: number;
    timestamp: Timestamp;
} {
    return {
        id: value.id,
        bmi: value.bmi,
        bmr: value.bmr,
        heightCm: value.heightCm,
        bmiCategory: from_candid_BMICategory_n39(_uploadFile, _downloadFile, value.bmiCategory),
        userId: value.userId,
        weightKg: value.weightKg,
        timestamp: value.timestamp
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bmiCategory: _BMICategory;
    latestBMI: number;
    latestBMR: number;
    dailyCaloricNeeds: number;
}): {
    bmiCategory: BMICategory;
    latestBMI: number;
    latestBMR: number;
    dailyCaloricNeeds: number;
} {
    return {
        bmiCategory: from_candid_BMICategory_n39(_uploadFile, _downloadFile, value.bmiCategory),
        latestBMI: value.latestBMI,
        latestBMR: value.latestBMR,
        dailyCaloricNeeds: value.dailyCaloricNeeds
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    fatG: number;
    calories: bigint;
    name: string;
    description: string;
    isVegetarian: boolean;
    category: _MealCategory;
    carbsG: number;
    prepTimeMinutes: bigint;
    proteinG: number;
}): {
    id: Id;
    fatG: number;
    calories: bigint;
    name: string;
    description: string;
    isVegetarian: boolean;
    category: MealCategory;
    carbsG: number;
    prepTimeMinutes: bigint;
    proteinG: number;
} {
    return {
        id: value.id,
        fatG: value.fatG,
        calories: value.calories,
        name: value.name,
        description: value.description,
        isVegetarian: value.isVegetarian,
        category: from_candid_MealCategory_n47(_uploadFile, _downloadFile, value.category),
        carbsG: value.carbsG,
        prepTimeMinutes: value.prepTimeMinutes,
        proteinG: value.proteinG
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    meals: Array<_Meal>;
    userId: _UserId;
    dailyCaloricTarget: bigint;
}): {
    meals: Array<Meal>;
    userId: UserId;
    dailyCaloricTarget: bigint;
} {
    return {
        meals: from_candid_vec_n53(_uploadFile, _downloadFile, value.meals),
        userId: value.userId,
        dailyCaloricTarget: value.dailyCaloricTarget
    };
}
function from_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    fitnessLevel: _FitnessLevel;
    exerciseIds: Array<_Id>;
    name: string;
    description: string;
}): {
    id: Id;
    fitnessLevel: FitnessLevel;
    exerciseIds: Array<Id>;
    name: string;
    description: string;
} {
    return {
        id: value.id,
        fitnessLevel: from_candid_FitnessLevel_n25(_uploadFile, _downloadFile, value.fitnessLevel),
        exerciseIds: value.exerciseIds,
        name: value.name,
        description: value.description
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Sedentary: null;
} | {
    VeryActive: null;
} | {
    LightlyActive: null;
} | {
    ModeratelyActive: null;
} | {
    ExtraActive: null;
}): ActivityLevel {
    return "Sedentary" in value ? ActivityLevel.Sedentary : "VeryActive" in value ? ActivityLevel.VeryActive : "LightlyActive" in value ? ActivityLevel.LightlyActive : "ModeratelyActive" in value ? ActivityLevel.ModeratelyActive : "ExtraActive" in value ? ActivityLevel.ExtraActive : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Maintain: null;
} | {
    GainWeight: null;
} | {
    LoseWeight: null;
}): Goal {
    return "Maintain" in value ? Goal.Maintain : "GainWeight" in value ? Goal.GainWeight : "LoseWeight" in value ? Goal.LoseWeight : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Male: null;
} | {
    Female: null;
}): Gender {
    return "Male" in value ? Gender.Male : "Female" in value ? Gender.Female : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Vegetarian: null;
} | {
    NonVegetarian: null;
}): DietaryPreference {
    return "Vegetarian" in value ? DietaryPreference.Vegetarian : "NonVegetarian" in value ? DietaryPreference.NonVegetarian : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Beginner: null;
} | {
    Advanced: null;
} | {
    Intermediate: null;
}): FitnessLevel {
    return "Beginner" in value ? FitnessLevel.Beginner : "Advanced" in value ? FitnessLevel.Advanced : "Intermediate" in value ? FitnessLevel.Intermediate : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Arms: null;
} | {
    Back: null;
} | {
    Core: null;
} | {
    FullBody: null;
} | {
    Legs: null;
} | {
    Chest: null;
} | {
    Cardio: null;
}): MuscleGroup {
    return "Arms" in value ? MuscleGroup.Arms : "Back" in value ? MuscleGroup.Back : "Core" in value ? MuscleGroup.Core : "FullBody" in value ? MuscleGroup.FullBody : "Legs" in value ? MuscleGroup.Legs : "Chest" in value ? MuscleGroup.Chest : "Cardio" in value ? MuscleGroup.Cardio : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Normal: null;
} | {
    Overweight: null;
} | {
    Obese: null;
} | {
    Underweight: null;
}): BMICategory {
    return "Normal" in value ? BMICategory.Normal : "Overweight" in value ? BMICategory.Overweight : "Obese" in value ? BMICategory.Obese : "Underweight" in value ? BMICategory.Underweight : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Lunch: null;
} | {
    Snack: null;
} | {
    Breakfast: null;
} | {
    Dinner: null;
}): MealCategory {
    return "Lunch" in value ? MealCategory.Lunch : "Snack" in value ? MealCategory.Snack : "Breakfast" in value ? MealCategory.Breakfast : "Dinner" in value ? MealCategory.Dinner : value;
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Exercise>): Array<Exercise> {
    return value.map((x)=>from_candid_Exercise_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HealthMetricLog>): Array<HealthMetricLog> {
    return value.map((x)=>from_candid_HealthMetricLog_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Meal>): Array<Meal> {
    return value.map((x)=>from_candid_Meal_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkoutRoutine>): Array<WorkoutRoutine> {
    return value.map((x)=>from_candid_WorkoutRoutine_n59(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityLevel_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityLevel): _ActivityLevel {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CreateProfileRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateProfileRequest): _CreateProfileRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_DietaryPreference_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietaryPreference): _DietaryPreference {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_FitnessLevel_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FitnessLevel): _FitnessLevel {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Goal_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Goal): _Goal {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_MealCategory_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MealCategory): _MealCategory {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function to_candid_MuscleGroup_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MuscleGroup): _MuscleGroup {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProfileRequest_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProfileRequest): _UpdateProfileRequest {
    return to_candid_record_n64(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MuscleGroup | null): [] | [_MuscleGroup] {
    return value === null ? candid_none() : candid_some(to_candid_MuscleGroup_n30(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FitnessLevel | null): [] | [_FitnessLevel] {
    return value === null ? candid_none() : candid_some(to_candid_FitnessLevel_n33(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MealCategory | null): [] | [_MealCategory] {
    return value === null ? candid_none() : candid_some(to_candid_MealCategory_n51(_uploadFile, _downloadFile, value));
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    activityLevel: ActivityLevel;
    heightCm: number;
    goal: Goal;
    name: string;
    weightKg: number;
    gender: Gender;
    dietaryPreference: DietaryPreference;
}): {
    age: bigint;
    activityLevel: _ActivityLevel;
    heightCm: number;
    goal: _Goal;
    name: string;
    weightKg: number;
    gender: _Gender;
    dietaryPreference: _DietaryPreference;
} {
    return {
        age: value.age,
        activityLevel: to_candid_ActivityLevel_n3(_uploadFile, _downloadFile, value.activityLevel),
        heightCm: value.heightCm,
        goal: to_candid_Goal_n5(_uploadFile, _downloadFile, value.goal),
        name: value.name,
        weightKg: value.weightKg,
        gender: to_candid_Gender_n7(_uploadFile, _downloadFile, value.gender),
        dietaryPreference: to_candid_DietaryPreference_n9(_uploadFile, _downloadFile, value.dietaryPreference)
    };
}
function to_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age?: bigint;
    activityLevel?: ActivityLevel;
    heightCm?: number;
    goal?: Goal;
    name?: string;
    weightKg?: number;
    gender?: Gender;
    dietaryPreference?: DietaryPreference;
}): {
    age: [] | [bigint];
    activityLevel: [] | [_ActivityLevel];
    heightCm: [] | [number];
    goal: [] | [_Goal];
    name: [] | [string];
    weightKg: [] | [number];
    gender: [] | [_Gender];
    dietaryPreference: [] | [_DietaryPreference];
} {
    return {
        age: value.age ? candid_some(value.age) : candid_none(),
        activityLevel: value.activityLevel ? candid_some(to_candid_ActivityLevel_n3(_uploadFile, _downloadFile, value.activityLevel)) : candid_none(),
        heightCm: value.heightCm ? candid_some(value.heightCm) : candid_none(),
        goal: value.goal ? candid_some(to_candid_Goal_n5(_uploadFile, _downloadFile, value.goal)) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        weightKg: value.weightKg ? candid_some(value.weightKg) : candid_none(),
        gender: value.gender ? candid_some(to_candid_Gender_n7(_uploadFile, _downloadFile, value.gender)) : candid_none(),
        dietaryPreference: value.dietaryPreference ? candid_some(to_candid_DietaryPreference_n9(_uploadFile, _downloadFile, value.dietaryPreference)) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietaryPreference): {
    Vegetarian: null;
} | {
    NonVegetarian: null;
} {
    return value == DietaryPreference.Vegetarian ? {
        Vegetarian: null
    } : value == DietaryPreference.NonVegetarian ? {
        NonVegetarian: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MuscleGroup): {
    Arms: null;
} | {
    Back: null;
} | {
    Core: null;
} | {
    FullBody: null;
} | {
    Legs: null;
} | {
    Chest: null;
} | {
    Cardio: null;
} {
    return value == MuscleGroup.Arms ? {
        Arms: null
    } : value == MuscleGroup.Back ? {
        Back: null
    } : value == MuscleGroup.Core ? {
        Core: null
    } : value == MuscleGroup.FullBody ? {
        FullBody: null
    } : value == MuscleGroup.Legs ? {
        Legs: null
    } : value == MuscleGroup.Chest ? {
        Chest: null
    } : value == MuscleGroup.Cardio ? {
        Cardio: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FitnessLevel): {
    Beginner: null;
} | {
    Advanced: null;
} | {
    Intermediate: null;
} {
    return value == FitnessLevel.Beginner ? {
        Beginner: null
    } : value == FitnessLevel.Advanced ? {
        Advanced: null
    } : value == FitnessLevel.Intermediate ? {
        Intermediate: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityLevel): {
    Sedentary: null;
} | {
    VeryActive: null;
} | {
    LightlyActive: null;
} | {
    ModeratelyActive: null;
} | {
    ExtraActive: null;
} {
    return value == ActivityLevel.Sedentary ? {
        Sedentary: null
    } : value == ActivityLevel.VeryActive ? {
        VeryActive: null
    } : value == ActivityLevel.LightlyActive ? {
        LightlyActive: null
    } : value == ActivityLevel.ModeratelyActive ? {
        ModeratelyActive: null
    } : value == ActivityLevel.ExtraActive ? {
        ExtraActive: null
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MealCategory): {
    Lunch: null;
} | {
    Snack: null;
} | {
    Breakfast: null;
} | {
    Dinner: null;
} {
    return value == MealCategory.Lunch ? {
        Lunch: null
    } : value == MealCategory.Snack ? {
        Snack: null
    } : value == MealCategory.Breakfast ? {
        Breakfast: null
    } : value == MealCategory.Dinner ? {
        Dinner: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Goal): {
    Maintain: null;
} | {
    GainWeight: null;
} | {
    LoseWeight: null;
} {
    return value == Goal.Maintain ? {
        Maintain: null
    } : value == Goal.GainWeight ? {
        GainWeight: null
    } : value == Goal.LoseWeight ? {
        LoseWeight: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    Male: null;
} | {
    Female: null;
} {
    return value == Gender.Male ? {
        Male: null
    } : value == Gender.Female ? {
        Female: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
